name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm install -g html-minifier-terser
          npm install -g clean-css-cli
          npm install -g uglify-js
          npm install -g svgo
          npm install -g imagemin-cli

      - name: Optimize assets
        run: |
          # Minify HTML
          find . -name "*.html" -exec html-minifier-terser --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css true --minify-js true {} -o {} \;
          
          # Optimize images
          find assets/images -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" -o -name "*.gif" \) -exec imagemin {} -o {} \;
          find assets/images -type f -name "*.svg" -exec svgo {} \;
          
          # Optimize CSS
          find assets/css -name "*.css" -exec cleancss -o {} {} \;
          
          # Optimize JavaScript
          find assets/js -name "*.js" -exec uglifyjs {} -o {} \;

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          clean: true
          single-commit: true 